apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: trillo
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      namespace: trillo
      labels:
        app: redis
    spec:
      containers:
        - image: redis
          name: redis
          command:
            - redis-server --requirepass tri_redbull --appendonly yes
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-persistent-storage
              mountPath: /data
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: trillo-rt-appdata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: trillo
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: redis
