apiVersion: apps/v1
kind: Deployment
metadata:
  name: trillo-redis
  namespace: trillo
  labels:
    app: trillo-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trillo-redis
  template:
    metadata:
      name: trillo-redis
      namespace: trillo
      labels:
        app: trillo-redis
    spec:
      containers:
        - image: redis
          name: trillo-redis
          command:
            - "redis-server"
          args:
            - "--requirepass"
            - "tri_redbull"
            - "--appendonly"
            - "yes"
          ports:
            - containerPort: 6379
              name: trillo-redis
          volumeMounts:
            - name: redis-persistent-storage
              mountPath: /data
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: trillo-rt-appdata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: trillo-redis
  namespace: trillo
  labels:
    app: trillo-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: trillo-redis
