kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-volumeclaim
  namespace: trillo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: repo-volumeclaim
  namespace: trillo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: appdata-volumeclaim
  namespace: trillo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
