apiVersion: v1
kind: ServiceAccount
metadata:
  name: trillo-rt
  namespace: trillo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trillo-rt-role-binding
  namespace: trillo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit # Allows read/write access to most objects in a namespace. It does not allow viewing or modifying roles or rolebindings.
subjects:
- kind: ServiceAccount
  name: trillo-rt
  namespace: trillo
